name           = "App-Greple-unicode-name"
badges         = [ "github-actions/test.yml", "metacpan" ]
module_maker   = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"

[unsupported]
os = [
    "MSWin32",
]
